FROM python:3.9
COPY requirements.txt /

# RUN pip install -r /requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
WORKDIR /app

EXPOSE 5000

CMD [ "python", "./server.py" ]
